// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'AboutMission': typeof import("../components/AboutMission.vue")['default'],
    'BrandLogoCarousel': typeof import("../components/BrandLogoCarousel.vue")['default'],
    'Breadcrumb': typeof import("../components/Breadcrumb.vue")['default'],
    'ContactInfo': typeof import("../components/ContactInfo.vue")['default'],
    'FunFact': typeof import("../components/FunFact.vue")['default'],
    'HeaderWithTopbar': typeof import("../components/HeaderWithTopbar.vue")['default'],
    'InstagramPostWrapper': typeof import("../components/InstagramPostWrapper.vue")['default'],
    'Intro': typeof import("../components/Intro.vue")['default'],
    'IntroMobile': typeof import("../components/IntroMobile.vue")['default'],
    'Loading': typeof import("../components/Loading.vue")['default'],
    'Location': typeof import("../components/Location.vue")['default'],
    'Login': typeof import("../components/Login.vue")['default'],
    'MiniCart': typeof import("../components/MiniCart.vue")['default'],
    'MobileBar': typeof import("../components/MobileBar.vue")['default'],
    'Navigation': typeof import("../components/Navigation.vue")['default'],
    'OffCanvasMobileMenu': typeof import("../components/OffCanvasMobileMenu.vue")['default'],
    'Paypal': typeof import("../components/Paypal.vue")['default'],
    'ProductDetailsDescriptionReview': typeof import("../components/ProductDetailsDescriptionReview.vue")['default'],
    'QuickView': typeof import("../components/QuickView.vue")['default'],
    'Register': typeof import("../components/Register.vue")['default'],
    'ResponsiveMobileMenu': typeof import("../components/ResponsiveMobileMenu.vue")['default'],
    'SectionTitleWithSubTitle': typeof import("../components/SectionTitleWithSubTitle.vue")['default'],
    'ShopSidebar': typeof import("../components/ShopSidebar.vue")['default'],
    'StripeElement': typeof import("../components/StripeElement.vue")['default'],
    'TeamMembers': typeof import("../components/TeamMembers.vue")['default'],
    'TestimonialOne': typeof import("../components/TestimonialOne.vue")['default'],
    'TheFooter': typeof import("../components/TheFooter.vue")['default'],
    'TheHeader': typeof import("../components/TheHeader.vue")['default'],
    'WelcomeMessage': typeof import("../components/WelcomeMessage.vue")['default'],
    'PolicyServicePolicyFour': typeof import("../components/policy/ServicePolicyFour.vue")['default'],
    'HeroSliderSix': typeof import("../components/hero/HeroSliderSix.vue")['default'],
    'BannerItem': typeof import("../components/banner/BannerItem.vue")['default'],
    'BannerStyleFour': typeof import("../components/banner/BannerStyleFour.vue")['default'],
    'BannerStyleOne': typeof import("../components/banner/BannerStyleOne.vue")['default'],
    'ProductDetailsWrapper': typeof import("../components/product/ProductDetailsWrapper.vue")['default'],
    'ProductGridItem': typeof import("../components/product/ProductGridItem.vue")['default'],
    'ProductGridItemTwo': typeof import("../components/product/ProductGridItemTwo.vue")['default'],
    'ProductGridStyleThree': typeof import("../components/product/ProductGridStyleThree.vue")['default'],
    'ProductWrapperCosmetics': typeof import("../components/product/ProductWrapperCosmetics.vue")['default'],
    'CrudAll': typeof import("../components/crud/All.vue")['default'],
    'CrudCoupons': typeof import("../components/crud/Coupons.vue")['default'],
    'CrudCreate': typeof import("../components/crud/Create.vue")['default'],
    'CrudEdit': typeof import("../components/crud/Edit.vue")['default'],
    'CrudNav': typeof import("../components/crud/Nav.vue")['default'],
    'CrudNote': typeof import("../components/crud/Note.vue")['default'],
    'CrudOrders': typeof import("../components/crud/Orders.vue")['default'],
    'CrudOrdersHistory': typeof import("../components/crud/OrdersHistory.vue")['default']
    'LazyAboutMission': typeof import("../components/AboutMission.vue")['default'],
    'LazyBrandLogoCarousel': typeof import("../components/BrandLogoCarousel.vue")['default'],
    'LazyBreadcrumb': typeof import("../components/Breadcrumb.vue")['default'],
    'LazyContactInfo': typeof import("../components/ContactInfo.vue")['default'],
    'LazyFunFact': typeof import("../components/FunFact.vue")['default'],
    'LazyHeaderWithTopbar': typeof import("../components/HeaderWithTopbar.vue")['default'],
    'LazyInstagramPostWrapper': typeof import("../components/InstagramPostWrapper.vue")['default'],
    'LazyIntro': typeof import("../components/Intro.vue")['default'],
    'LazyIntroMobile': typeof import("../components/IntroMobile.vue")['default'],
    'LazyLoading': typeof import("../components/Loading.vue")['default'],
    'LazyLocation': typeof import("../components/Location.vue")['default'],
    'LazyLogin': typeof import("../components/Login.vue")['default'],
    'LazyMiniCart': typeof import("../components/MiniCart.vue")['default'],
    'LazyMobileBar': typeof import("../components/MobileBar.vue")['default'],
    'LazyNavigation': typeof import("../components/Navigation.vue")['default'],
    'LazyOffCanvasMobileMenu': typeof import("../components/OffCanvasMobileMenu.vue")['default'],
    'LazyPaypal': typeof import("../components/Paypal.vue")['default'],
    'LazyProductDetailsDescriptionReview': typeof import("../components/ProductDetailsDescriptionReview.vue")['default'],
    'LazyQuickView': typeof import("../components/QuickView.vue")['default'],
    'LazyRegister': typeof import("../components/Register.vue")['default'],
    'LazyResponsiveMobileMenu': typeof import("../components/ResponsiveMobileMenu.vue")['default'],
    'LazySectionTitleWithSubTitle': typeof import("../components/SectionTitleWithSubTitle.vue")['default'],
    'LazyShopSidebar': typeof import("../components/ShopSidebar.vue")['default'],
    'LazyStripeElement': typeof import("../components/StripeElement.vue")['default'],
    'LazyTeamMembers': typeof import("../components/TeamMembers.vue")['default'],
    'LazyTestimonialOne': typeof import("../components/TestimonialOne.vue")['default'],
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default'],
    'LazyTheHeader': typeof import("../components/TheHeader.vue")['default'],
    'LazyWelcomeMessage': typeof import("../components/WelcomeMessage.vue")['default'],
    'LazyPolicyServicePolicyFour': typeof import("../components/policy/ServicePolicyFour.vue")['default'],
    'LazyHeroSliderSix': typeof import("../components/hero/HeroSliderSix.vue")['default'],
    'LazyBannerItem': typeof import("../components/banner/BannerItem.vue")['default'],
    'LazyBannerStyleFour': typeof import("../components/banner/BannerStyleFour.vue")['default'],
    'LazyBannerStyleOne': typeof import("../components/banner/BannerStyleOne.vue")['default'],
    'LazyProductDetailsWrapper': typeof import("../components/product/ProductDetailsWrapper.vue")['default'],
    'LazyProductGridItem': typeof import("../components/product/ProductGridItem.vue")['default'],
    'LazyProductGridItemTwo': typeof import("../components/product/ProductGridItemTwo.vue")['default'],
    'LazyProductGridStyleThree': typeof import("../components/product/ProductGridStyleThree.vue")['default'],
    'LazyProductWrapperCosmetics': typeof import("../components/product/ProductWrapperCosmetics.vue")['default'],
    'LazyCrudAll': typeof import("../components/crud/All.vue")['default'],
    'LazyCrudCoupons': typeof import("../components/crud/Coupons.vue")['default'],
    'LazyCrudCreate': typeof import("../components/crud/Create.vue")['default'],
    'LazyCrudEdit': typeof import("../components/crud/Edit.vue")['default'],
    'LazyCrudNav': typeof import("../components/crud/Nav.vue")['default'],
    'LazyCrudNote': typeof import("../components/crud/Note.vue")['default'],
    'LazyCrudOrders': typeof import("../components/crud/Orders.vue")['default'],
    'LazyCrudOrdersHistory': typeof import("../components/crud/OrdersHistory.vue")['default']
  }
}
export const AboutMission: typeof import("../components/AboutMission.vue")['default']
export const BrandLogoCarousel: typeof import("../components/BrandLogoCarousel.vue")['default']
export const Breadcrumb: typeof import("../components/Breadcrumb.vue")['default']
export const ContactInfo: typeof import("../components/ContactInfo.vue")['default']
export const FunFact: typeof import("../components/FunFact.vue")['default']
export const HeaderWithTopbar: typeof import("../components/HeaderWithTopbar.vue")['default']
export const InstagramPostWrapper: typeof import("../components/InstagramPostWrapper.vue")['default']
export const Intro: typeof import("../components/Intro.vue")['default']
export const IntroMobile: typeof import("../components/IntroMobile.vue")['default']
export const Loading: typeof import("../components/Loading.vue")['default']
export const Location: typeof import("../components/Location.vue")['default']
export const Login: typeof import("../components/Login.vue")['default']
export const MiniCart: typeof import("../components/MiniCart.vue")['default']
export const MobileBar: typeof import("../components/MobileBar.vue")['default']
export const Navigation: typeof import("../components/Navigation.vue")['default']
export const OffCanvasMobileMenu: typeof import("../components/OffCanvasMobileMenu.vue")['default']
export const Paypal: typeof import("../components/Paypal.vue")['default']
export const ProductDetailsDescriptionReview: typeof import("../components/ProductDetailsDescriptionReview.vue")['default']
export const QuickView: typeof import("../components/QuickView.vue")['default']
export const Register: typeof import("../components/Register.vue")['default']
export const ResponsiveMobileMenu: typeof import("../components/ResponsiveMobileMenu.vue")['default']
export const SectionTitleWithSubTitle: typeof import("../components/SectionTitleWithSubTitle.vue")['default']
export const ShopSidebar: typeof import("../components/ShopSidebar.vue")['default']
export const StripeElement: typeof import("../components/StripeElement.vue")['default']
export const TeamMembers: typeof import("../components/TeamMembers.vue")['default']
export const TestimonialOne: typeof import("../components/TestimonialOne.vue")['default']
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const TheHeader: typeof import("../components/TheHeader.vue")['default']
export const WelcomeMessage: typeof import("../components/WelcomeMessage.vue")['default']
export const PolicyServicePolicyFour: typeof import("../components/policy/ServicePolicyFour.vue")['default']
export const HeroSliderSix: typeof import("../components/hero/HeroSliderSix.vue")['default']
export const BannerItem: typeof import("../components/banner/BannerItem.vue")['default']
export const BannerStyleFour: typeof import("../components/banner/BannerStyleFour.vue")['default']
export const BannerStyleOne: typeof import("../components/banner/BannerStyleOne.vue")['default']
export const ProductDetailsWrapper: typeof import("../components/product/ProductDetailsWrapper.vue")['default']
export const ProductGridItem: typeof import("../components/product/ProductGridItem.vue")['default']
export const ProductGridItemTwo: typeof import("../components/product/ProductGridItemTwo.vue")['default']
export const ProductGridStyleThree: typeof import("../components/product/ProductGridStyleThree.vue")['default']
export const ProductWrapperCosmetics: typeof import("../components/product/ProductWrapperCosmetics.vue")['default']
export const CrudAll: typeof import("../components/crud/All.vue")['default']
export const CrudCoupons: typeof import("../components/crud/Coupons.vue")['default']
export const CrudCreate: typeof import("../components/crud/Create.vue")['default']
export const CrudEdit: typeof import("../components/crud/Edit.vue")['default']
export const CrudNav: typeof import("../components/crud/Nav.vue")['default']
export const CrudNote: typeof import("../components/crud/Note.vue")['default']
export const CrudOrders: typeof import("../components/crud/Orders.vue")['default']
export const CrudOrdersHistory: typeof import("../components/crud/OrdersHistory.vue")['default']
export const LazyAboutMission: typeof import("../components/AboutMission.vue")['default']
export const LazyBrandLogoCarousel: typeof import("../components/BrandLogoCarousel.vue")['default']
export const LazyBreadcrumb: typeof import("../components/Breadcrumb.vue")['default']
export const LazyContactInfo: typeof import("../components/ContactInfo.vue")['default']
export const LazyFunFact: typeof import("../components/FunFact.vue")['default']
export const LazyHeaderWithTopbar: typeof import("../components/HeaderWithTopbar.vue")['default']
export const LazyInstagramPostWrapper: typeof import("../components/InstagramPostWrapper.vue")['default']
export const LazyIntro: typeof import("../components/Intro.vue")['default']
export const LazyIntroMobile: typeof import("../components/IntroMobile.vue")['default']
export const LazyLoading: typeof import("../components/Loading.vue")['default']
export const LazyLocation: typeof import("../components/Location.vue")['default']
export const LazyLogin: typeof import("../components/Login.vue")['default']
export const LazyMiniCart: typeof import("../components/MiniCart.vue")['default']
export const LazyMobileBar: typeof import("../components/MobileBar.vue")['default']
export const LazyNavigation: typeof import("../components/Navigation.vue")['default']
export const LazyOffCanvasMobileMenu: typeof import("../components/OffCanvasMobileMenu.vue")['default']
export const LazyPaypal: typeof import("../components/Paypal.vue")['default']
export const LazyProductDetailsDescriptionReview: typeof import("../components/ProductDetailsDescriptionReview.vue")['default']
export const LazyQuickView: typeof import("../components/QuickView.vue")['default']
export const LazyRegister: typeof import("../components/Register.vue")['default']
export const LazyResponsiveMobileMenu: typeof import("../components/ResponsiveMobileMenu.vue")['default']
export const LazySectionTitleWithSubTitle: typeof import("../components/SectionTitleWithSubTitle.vue")['default']
export const LazyShopSidebar: typeof import("../components/ShopSidebar.vue")['default']
export const LazyStripeElement: typeof import("../components/StripeElement.vue")['default']
export const LazyTeamMembers: typeof import("../components/TeamMembers.vue")['default']
export const LazyTestimonialOne: typeof import("../components/TestimonialOne.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyTheHeader: typeof import("../components/TheHeader.vue")['default']
export const LazyWelcomeMessage: typeof import("../components/WelcomeMessage.vue")['default']
export const LazyPolicyServicePolicyFour: typeof import("../components/policy/ServicePolicyFour.vue")['default']
export const LazyHeroSliderSix: typeof import("../components/hero/HeroSliderSix.vue")['default']
export const LazyBannerItem: typeof import("../components/banner/BannerItem.vue")['default']
export const LazyBannerStyleFour: typeof import("../components/banner/BannerStyleFour.vue")['default']
export const LazyBannerStyleOne: typeof import("../components/banner/BannerStyleOne.vue")['default']
export const LazyProductDetailsWrapper: typeof import("../components/product/ProductDetailsWrapper.vue")['default']
export const LazyProductGridItem: typeof import("../components/product/ProductGridItem.vue")['default']
export const LazyProductGridItemTwo: typeof import("../components/product/ProductGridItemTwo.vue")['default']
export const LazyProductGridStyleThree: typeof import("../components/product/ProductGridStyleThree.vue")['default']
export const LazyProductWrapperCosmetics: typeof import("../components/product/ProductWrapperCosmetics.vue")['default']
export const LazyCrudAll: typeof import("../components/crud/All.vue")['default']
export const LazyCrudCoupons: typeof import("../components/crud/Coupons.vue")['default']
export const LazyCrudCreate: typeof import("../components/crud/Create.vue")['default']
export const LazyCrudEdit: typeof import("../components/crud/Edit.vue")['default']
export const LazyCrudNav: typeof import("../components/crud/Nav.vue")['default']
export const LazyCrudNote: typeof import("../components/crud/Note.vue")['default']
export const LazyCrudOrders: typeof import("../components/crud/Orders.vue")['default']
export const LazyCrudOrdersHistory: typeof import("../components/crud/OrdersHistory.vue")['default']
export const componentNames: string[]
