// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'AboutMission': typeof import("../components/AboutMission.vue")['default'],
    'Auth': typeof import("../components/Auth.vue")['default'],
    'BlogItem': typeof import("../components/BlogItem.vue")['default'],
    'BlogItemStyleTwo': typeof import("../components/BlogItemStyleTwo.vue")['default'],
    'BlogSidebar': typeof import("../components/BlogSidebar.vue")['default'],
    'BlogWrapper': typeof import("../components/BlogWrapper.vue")['default'],
    'Breadcrumb': typeof import("../components/Breadcrumb.vue")['default'],
    'CheckoutContainer': typeof import("../components/CheckoutContainer.vue")['default'],
    'ContactInfo': typeof import("../components/ContactInfo.vue")['default'],
    'ContactModal': typeof import("../components/ContactModal.vue")['default'],
    'CookiesPolicyContent': typeof import("../components/CookiesPolicyContent.vue")['default'],
    'Countdown': typeof import("../components/Countdown.vue")['default'],
    'CountdownMini': typeof import("../components/CountdownMini.vue")['default'],
    'CountdownShop': typeof import("../components/CountdownShop.vue")['default'],
    'ForgotPasswordContainer': typeof import("../components/ForgotPasswordContainer.vue")['default'],
    'GiftModal': typeof import("../components/GiftModal.vue")['default'],
    'HeaderWithTopbar': typeof import("../components/HeaderWithTopbar.vue")['default'],
    'IconsActions': typeof import("../components/IconsActions.vue")['default'],
    'Intro': typeof import("../components/Intro.vue")['default'],
    'IntroMobile': typeof import("../components/IntroMobile.vue")['default'],
    'LegalWarningProtectionDatesContainer': typeof import("../components/LegalWarningProtectionDatesContainer.vue")['default'],
    'Location': typeof import("../components/Location.vue")['default'],
    'Login': typeof import("../components/Login.vue")['default'],
    'MiniCart': typeof import("../components/MiniCart.vue")['default'],
    'MobileBar': typeof import("../components/MobileBar.vue")['default'],
    'ModalError': typeof import("../components/ModalError.vue")['default'],
    'MyAccountContainer': typeof import("../components/MyAccountContainer.vue")['default'],
    'MyOrdersCom': typeof import("../components/MyOrdersCom.vue")['default'],
    'NavBottom': typeof import("../components/NavBottom.vue")['default'],
    'Navigation': typeof import("../components/Navigation.vue")['default'],
    'NewsletterModal': typeof import("../components/NewsletterModal.vue")['default'],
    'Notifications': typeof import("../components/Notifications.vue")['default'],
    'NotificationsContent': typeof import("../components/NotificationsContent.vue")['default'],
    'OffCanvasMobileMenu': typeof import("../components/OffCanvasMobileMenu.vue")['default'],
    'OrderConfirmation': typeof import("../components/OrderConfirmation.vue")['default'],
    'OrdersCom': typeof import("../components/OrdersCom.vue")['default'],
    'OrdersProfileCom': typeof import("../components/OrdersProfileCom.vue")['default'],
    'ProductDetailsDescriptionReview': typeof import("../components/ProductDetailsDescriptionReview.vue")['default'],
    'QuestionsCont': typeof import("../components/QuestionsCont.vue")['default'],
    'Register': typeof import("../components/Register.vue")['default'],
    'ResponsiveMobileMenu': typeof import("../components/ResponsiveMobileMenu.vue")['default'],
    'Reviews': typeof import("../components/Reviews.vue")['default'],
    'Search': typeof import("../components/Search.vue")['default'],
    'ShopContainer': typeof import("../components/ShopContainer.vue")['default'],
    'ShopSidebar': typeof import("../components/ShopSidebar.vue")['default'],
    'SuggestionsModal': typeof import("../components/SuggestionsModal.vue")['default'],
    'TermsConditionsContainer': typeof import("../components/TermsConditionsContainer.vue")['default'],
    'Testimonials': typeof import("../components/Testimonials.vue")['default'],
    'TheFooter': typeof import("../components/TheFooter.vue")['default'],
    'TheHeader': typeof import("../components/TheHeader.vue")['default'],
    'UnsubscribeContainer': typeof import("../components/UnsubscribeContainer.vue")['default'],
    'WelcomeMessage': typeof import("../components/WelcomeMessage.vue")['default'],
    'WishListContainer': typeof import("../components/WishListContainer.vue")['default'],
    'CheckoutAddressStep': typeof import("../components/checkout/AddressStep.vue")['default'],
    'CheckoutCouponForm': typeof import("../components/checkout/CouponForm.vue")['default'],
    'CheckoutEmailStep': typeof import("../components/checkout/EmailStep.vue")['default'],
    'CheckoutNewProgressBar': typeof import("../components/checkout/NewProgressBar.vue")['default'],
    'CheckoutPayStep': typeof import("../components/checkout/PayStep.vue")['default'],
    'CheckoutPaypal': typeof import("../components/checkout/Paypal.vue")['default'],
    'CheckoutPickupModal': typeof import("../components/checkout/PickupModal.vue")['default'],
    'CheckoutRedsysPay': typeof import("../components/checkout/RedsysPay.vue")['default'],
    'CheckoutResumen': typeof import("../components/checkout/Resumen.vue")['default'],
    'CheckoutSendStep': typeof import("../components/checkout/SendStep.vue")['default'],
    'CheckoutSuccessOrder': typeof import("../components/checkout/SuccessOrder.vue")['default'],
    'CheckoutTimerNav': typeof import("../components/checkout/TimerNav.vue")['default'],
    'HeaderCheckout': typeof import("../components/header/HeaderCheckout.vue")['default'],
    'HeroSliderSix': typeof import("../components/hero/HeroSliderSix.vue")['default'],
    'PolicyServicePolicyFour': typeof import("../components/policy/ServicePolicyFour.vue")['default'],
    'LoadersBigLoader': typeof import("../components/loaders/BigLoader.vue")['default'],
    'LoadersSmallLoading': typeof import("../components/loaders/SmallLoading.vue")['default'],
    'ProfileNewGuest': typeof import("../components/profile/NewGuest.vue")['default'],
    'ProfileNewProfile': typeof import("../components/profile/NewProfile.vue")['default'],
    'ProductDetailsWrapper': typeof import("../components/product/ProductDetailsWrapper.vue")['default'],
    'ProductGridItem': typeof import("../components/product/ProductGridItem.vue")['default'],
    'ProductGridItemTwo': typeof import("../components/product/ProductGridItemTwo.vue")['default'],
    'ProductGridStyleThree': typeof import("../components/product/ProductGridStyleThree.vue")['default'],
    'ProductWrapperCosmetics': typeof import("../components/product/ProductWrapperCosmetics.vue")['default'],
    'ProductWrapperCosmeticsCart': typeof import("../components/product/ProductWrapperCosmeticsCart.vue")['default'],
    'ProductWrapperCosmeticsTwo': typeof import("../components/product/ProductWrapperCosmeticsTwo.vue")['default'],
    'ProductWrapperCosmeticsTwoDetail': typeof import("../components/product/ProductWrapperCosmeticsTwoDetail.vue")['default']
    'LazyAboutMission': typeof import("../components/AboutMission.vue")['default'],
    'LazyAuth': typeof import("../components/Auth.vue")['default'],
    'LazyBlogItem': typeof import("../components/BlogItem.vue")['default'],
    'LazyBlogItemStyleTwo': typeof import("../components/BlogItemStyleTwo.vue")['default'],
    'LazyBlogSidebar': typeof import("../components/BlogSidebar.vue")['default'],
    'LazyBlogWrapper': typeof import("../components/BlogWrapper.vue")['default'],
    'LazyBreadcrumb': typeof import("../components/Breadcrumb.vue")['default'],
    'LazyCheckoutContainer': typeof import("../components/CheckoutContainer.vue")['default'],
    'LazyContactInfo': typeof import("../components/ContactInfo.vue")['default'],
    'LazyContactModal': typeof import("../components/ContactModal.vue")['default'],
    'LazyCookiesPolicyContent': typeof import("../components/CookiesPolicyContent.vue")['default'],
    'LazyCountdown': typeof import("../components/Countdown.vue")['default'],
    'LazyCountdownMini': typeof import("../components/CountdownMini.vue")['default'],
    'LazyCountdownShop': typeof import("../components/CountdownShop.vue")['default'],
    'LazyForgotPasswordContainer': typeof import("../components/ForgotPasswordContainer.vue")['default'],
    'LazyGiftModal': typeof import("../components/GiftModal.vue")['default'],
    'LazyHeaderWithTopbar': typeof import("../components/HeaderWithTopbar.vue")['default'],
    'LazyIconsActions': typeof import("../components/IconsActions.vue")['default'],
    'LazyIntro': typeof import("../components/Intro.vue")['default'],
    'LazyIntroMobile': typeof import("../components/IntroMobile.vue")['default'],
    'LazyLegalWarningProtectionDatesContainer': typeof import("../components/LegalWarningProtectionDatesContainer.vue")['default'],
    'LazyLocation': typeof import("../components/Location.vue")['default'],
    'LazyLogin': typeof import("../components/Login.vue")['default'],
    'LazyMiniCart': typeof import("../components/MiniCart.vue")['default'],
    'LazyMobileBar': typeof import("../components/MobileBar.vue")['default'],
    'LazyModalError': typeof import("../components/ModalError.vue")['default'],
    'LazyMyAccountContainer': typeof import("../components/MyAccountContainer.vue")['default'],
    'LazyMyOrdersCom': typeof import("../components/MyOrdersCom.vue")['default'],
    'LazyNavBottom': typeof import("../components/NavBottom.vue")['default'],
    'LazyNavigation': typeof import("../components/Navigation.vue")['default'],
    'LazyNewsletterModal': typeof import("../components/NewsletterModal.vue")['default'],
    'LazyNotifications': typeof import("../components/Notifications.vue")['default'],
    'LazyNotificationsContent': typeof import("../components/NotificationsContent.vue")['default'],
    'LazyOffCanvasMobileMenu': typeof import("../components/OffCanvasMobileMenu.vue")['default'],
    'LazyOrderConfirmation': typeof import("../components/OrderConfirmation.vue")['default'],
    'LazyOrdersCom': typeof import("../components/OrdersCom.vue")['default'],
    'LazyOrdersProfileCom': typeof import("../components/OrdersProfileCom.vue")['default'],
    'LazyProductDetailsDescriptionReview': typeof import("../components/ProductDetailsDescriptionReview.vue")['default'],
    'LazyQuestionsCont': typeof import("../components/QuestionsCont.vue")['default'],
    'LazyRegister': typeof import("../components/Register.vue")['default'],
    'LazyResponsiveMobileMenu': typeof import("../components/ResponsiveMobileMenu.vue")['default'],
    'LazyReviews': typeof import("../components/Reviews.vue")['default'],
    'LazySearch': typeof import("../components/Search.vue")['default'],
    'LazyShopContainer': typeof import("../components/ShopContainer.vue")['default'],
    'LazyShopSidebar': typeof import("../components/ShopSidebar.vue")['default'],
    'LazySuggestionsModal': typeof import("../components/SuggestionsModal.vue")['default'],
    'LazyTermsConditionsContainer': typeof import("../components/TermsConditionsContainer.vue")['default'],
    'LazyTestimonials': typeof import("../components/Testimonials.vue")['default'],
    'LazyTheFooter': typeof import("../components/TheFooter.vue")['default'],
    'LazyTheHeader': typeof import("../components/TheHeader.vue")['default'],
    'LazyUnsubscribeContainer': typeof import("../components/UnsubscribeContainer.vue")['default'],
    'LazyWelcomeMessage': typeof import("../components/WelcomeMessage.vue")['default'],
    'LazyWishListContainer': typeof import("../components/WishListContainer.vue")['default'],
    'LazyCheckoutAddressStep': typeof import("../components/checkout/AddressStep.vue")['default'],
    'LazyCheckoutCouponForm': typeof import("../components/checkout/CouponForm.vue")['default'],
    'LazyCheckoutEmailStep': typeof import("../components/checkout/EmailStep.vue")['default'],
    'LazyCheckoutNewProgressBar': typeof import("../components/checkout/NewProgressBar.vue")['default'],
    'LazyCheckoutPayStep': typeof import("../components/checkout/PayStep.vue")['default'],
    'LazyCheckoutPaypal': typeof import("../components/checkout/Paypal.vue")['default'],
    'LazyCheckoutPickupModal': typeof import("../components/checkout/PickupModal.vue")['default'],
    'LazyCheckoutRedsysPay': typeof import("../components/checkout/RedsysPay.vue")['default'],
    'LazyCheckoutResumen': typeof import("../components/checkout/Resumen.vue")['default'],
    'LazyCheckoutSendStep': typeof import("../components/checkout/SendStep.vue")['default'],
    'LazyCheckoutSuccessOrder': typeof import("../components/checkout/SuccessOrder.vue")['default'],
    'LazyCheckoutTimerNav': typeof import("../components/checkout/TimerNav.vue")['default'],
    'LazyHeaderCheckout': typeof import("../components/header/HeaderCheckout.vue")['default'],
    'LazyHeroSliderSix': typeof import("../components/hero/HeroSliderSix.vue")['default'],
    'LazyPolicyServicePolicyFour': typeof import("../components/policy/ServicePolicyFour.vue")['default'],
    'LazyLoadersBigLoader': typeof import("../components/loaders/BigLoader.vue")['default'],
    'LazyLoadersSmallLoading': typeof import("../components/loaders/SmallLoading.vue")['default'],
    'LazyProfileNewGuest': typeof import("../components/profile/NewGuest.vue")['default'],
    'LazyProfileNewProfile': typeof import("../components/profile/NewProfile.vue")['default'],
    'LazyProductDetailsWrapper': typeof import("../components/product/ProductDetailsWrapper.vue")['default'],
    'LazyProductGridItem': typeof import("../components/product/ProductGridItem.vue")['default'],
    'LazyProductGridItemTwo': typeof import("../components/product/ProductGridItemTwo.vue")['default'],
    'LazyProductGridStyleThree': typeof import("../components/product/ProductGridStyleThree.vue")['default'],
    'LazyProductWrapperCosmetics': typeof import("../components/product/ProductWrapperCosmetics.vue")['default'],
    'LazyProductWrapperCosmeticsCart': typeof import("../components/product/ProductWrapperCosmeticsCart.vue")['default'],
    'LazyProductWrapperCosmeticsTwo': typeof import("../components/product/ProductWrapperCosmeticsTwo.vue")['default'],
    'LazyProductWrapperCosmeticsTwoDetail': typeof import("../components/product/ProductWrapperCosmeticsTwoDetail.vue")['default']
  }
}
export const AboutMission: typeof import("../components/AboutMission.vue")['default']
export const Auth: typeof import("../components/Auth.vue")['default']
export const BlogItem: typeof import("../components/BlogItem.vue")['default']
export const BlogItemStyleTwo: typeof import("../components/BlogItemStyleTwo.vue")['default']
export const BlogSidebar: typeof import("../components/BlogSidebar.vue")['default']
export const BlogWrapper: typeof import("../components/BlogWrapper.vue")['default']
export const Breadcrumb: typeof import("../components/Breadcrumb.vue")['default']
export const CheckoutContainer: typeof import("../components/CheckoutContainer.vue")['default']
export const ContactInfo: typeof import("../components/ContactInfo.vue")['default']
export const ContactModal: typeof import("../components/ContactModal.vue")['default']
export const CookiesPolicyContent: typeof import("../components/CookiesPolicyContent.vue")['default']
export const Countdown: typeof import("../components/Countdown.vue")['default']
export const CountdownMini: typeof import("../components/CountdownMini.vue")['default']
export const CountdownShop: typeof import("../components/CountdownShop.vue")['default']
export const ForgotPasswordContainer: typeof import("../components/ForgotPasswordContainer.vue")['default']
export const GiftModal: typeof import("../components/GiftModal.vue")['default']
export const HeaderWithTopbar: typeof import("../components/HeaderWithTopbar.vue")['default']
export const IconsActions: typeof import("../components/IconsActions.vue")['default']
export const Intro: typeof import("../components/Intro.vue")['default']
export const IntroMobile: typeof import("../components/IntroMobile.vue")['default']
export const LegalWarningProtectionDatesContainer: typeof import("../components/LegalWarningProtectionDatesContainer.vue")['default']
export const Location: typeof import("../components/Location.vue")['default']
export const Login: typeof import("../components/Login.vue")['default']
export const MiniCart: typeof import("../components/MiniCart.vue")['default']
export const MobileBar: typeof import("../components/MobileBar.vue")['default']
export const ModalError: typeof import("../components/ModalError.vue")['default']
export const MyAccountContainer: typeof import("../components/MyAccountContainer.vue")['default']
export const MyOrdersCom: typeof import("../components/MyOrdersCom.vue")['default']
export const NavBottom: typeof import("../components/NavBottom.vue")['default']
export const Navigation: typeof import("../components/Navigation.vue")['default']
export const NewsletterModal: typeof import("../components/NewsletterModal.vue")['default']
export const Notifications: typeof import("../components/Notifications.vue")['default']
export const NotificationsContent: typeof import("../components/NotificationsContent.vue")['default']
export const OffCanvasMobileMenu: typeof import("../components/OffCanvasMobileMenu.vue")['default']
export const OrderConfirmation: typeof import("../components/OrderConfirmation.vue")['default']
export const OrdersCom: typeof import("../components/OrdersCom.vue")['default']
export const OrdersProfileCom: typeof import("../components/OrdersProfileCom.vue")['default']
export const ProductDetailsDescriptionReview: typeof import("../components/ProductDetailsDescriptionReview.vue")['default']
export const QuestionsCont: typeof import("../components/QuestionsCont.vue")['default']
export const Register: typeof import("../components/Register.vue")['default']
export const ResponsiveMobileMenu: typeof import("../components/ResponsiveMobileMenu.vue")['default']
export const Reviews: typeof import("../components/Reviews.vue")['default']
export const Search: typeof import("../components/Search.vue")['default']
export const ShopContainer: typeof import("../components/ShopContainer.vue")['default']
export const ShopSidebar: typeof import("../components/ShopSidebar.vue")['default']
export const SuggestionsModal: typeof import("../components/SuggestionsModal.vue")['default']
export const TermsConditionsContainer: typeof import("../components/TermsConditionsContainer.vue")['default']
export const Testimonials: typeof import("../components/Testimonials.vue")['default']
export const TheFooter: typeof import("../components/TheFooter.vue")['default']
export const TheHeader: typeof import("../components/TheHeader.vue")['default']
export const UnsubscribeContainer: typeof import("../components/UnsubscribeContainer.vue")['default']
export const WelcomeMessage: typeof import("../components/WelcomeMessage.vue")['default']
export const WishListContainer: typeof import("../components/WishListContainer.vue")['default']
export const CheckoutAddressStep: typeof import("../components/checkout/AddressStep.vue")['default']
export const CheckoutCouponForm: typeof import("../components/checkout/CouponForm.vue")['default']
export const CheckoutEmailStep: typeof import("../components/checkout/EmailStep.vue")['default']
export const CheckoutNewProgressBar: typeof import("../components/checkout/NewProgressBar.vue")['default']
export const CheckoutPayStep: typeof import("../components/checkout/PayStep.vue")['default']
export const CheckoutPaypal: typeof import("../components/checkout/Paypal.vue")['default']
export const CheckoutPickupModal: typeof import("../components/checkout/PickupModal.vue")['default']
export const CheckoutRedsysPay: typeof import("../components/checkout/RedsysPay.vue")['default']
export const CheckoutResumen: typeof import("../components/checkout/Resumen.vue")['default']
export const CheckoutSendStep: typeof import("../components/checkout/SendStep.vue")['default']
export const CheckoutSuccessOrder: typeof import("../components/checkout/SuccessOrder.vue")['default']
export const CheckoutTimerNav: typeof import("../components/checkout/TimerNav.vue")['default']
export const HeaderCheckout: typeof import("../components/header/HeaderCheckout.vue")['default']
export const HeroSliderSix: typeof import("../components/hero/HeroSliderSix.vue")['default']
export const PolicyServicePolicyFour: typeof import("../components/policy/ServicePolicyFour.vue")['default']
export const LoadersBigLoader: typeof import("../components/loaders/BigLoader.vue")['default']
export const LoadersSmallLoading: typeof import("../components/loaders/SmallLoading.vue")['default']
export const ProfileNewGuest: typeof import("../components/profile/NewGuest.vue")['default']
export const ProfileNewProfile: typeof import("../components/profile/NewProfile.vue")['default']
export const ProductDetailsWrapper: typeof import("../components/product/ProductDetailsWrapper.vue")['default']
export const ProductGridItem: typeof import("../components/product/ProductGridItem.vue")['default']
export const ProductGridItemTwo: typeof import("../components/product/ProductGridItemTwo.vue")['default']
export const ProductGridStyleThree: typeof import("../components/product/ProductGridStyleThree.vue")['default']
export const ProductWrapperCosmetics: typeof import("../components/product/ProductWrapperCosmetics.vue")['default']
export const ProductWrapperCosmeticsCart: typeof import("../components/product/ProductWrapperCosmeticsCart.vue")['default']
export const ProductWrapperCosmeticsTwo: typeof import("../components/product/ProductWrapperCosmeticsTwo.vue")['default']
export const ProductWrapperCosmeticsTwoDetail: typeof import("../components/product/ProductWrapperCosmeticsTwoDetail.vue")['default']
export const LazyAboutMission: typeof import("../components/AboutMission.vue")['default']
export const LazyAuth: typeof import("../components/Auth.vue")['default']
export const LazyBlogItem: typeof import("../components/BlogItem.vue")['default']
export const LazyBlogItemStyleTwo: typeof import("../components/BlogItemStyleTwo.vue")['default']
export const LazyBlogSidebar: typeof import("../components/BlogSidebar.vue")['default']
export const LazyBlogWrapper: typeof import("../components/BlogWrapper.vue")['default']
export const LazyBreadcrumb: typeof import("../components/Breadcrumb.vue")['default']
export const LazyCheckoutContainer: typeof import("../components/CheckoutContainer.vue")['default']
export const LazyContactInfo: typeof import("../components/ContactInfo.vue")['default']
export const LazyContactModal: typeof import("../components/ContactModal.vue")['default']
export const LazyCookiesPolicyContent: typeof import("../components/CookiesPolicyContent.vue")['default']
export const LazyCountdown: typeof import("../components/Countdown.vue")['default']
export const LazyCountdownMini: typeof import("../components/CountdownMini.vue")['default']
export const LazyCountdownShop: typeof import("../components/CountdownShop.vue")['default']
export const LazyForgotPasswordContainer: typeof import("../components/ForgotPasswordContainer.vue")['default']
export const LazyGiftModal: typeof import("../components/GiftModal.vue")['default']
export const LazyHeaderWithTopbar: typeof import("../components/HeaderWithTopbar.vue")['default']
export const LazyIconsActions: typeof import("../components/IconsActions.vue")['default']
export const LazyIntro: typeof import("../components/Intro.vue")['default']
export const LazyIntroMobile: typeof import("../components/IntroMobile.vue")['default']
export const LazyLegalWarningProtectionDatesContainer: typeof import("../components/LegalWarningProtectionDatesContainer.vue")['default']
export const LazyLocation: typeof import("../components/Location.vue")['default']
export const LazyLogin: typeof import("../components/Login.vue")['default']
export const LazyMiniCart: typeof import("../components/MiniCart.vue")['default']
export const LazyMobileBar: typeof import("../components/MobileBar.vue")['default']
export const LazyModalError: typeof import("../components/ModalError.vue")['default']
export const LazyMyAccountContainer: typeof import("../components/MyAccountContainer.vue")['default']
export const LazyMyOrdersCom: typeof import("../components/MyOrdersCom.vue")['default']
export const LazyNavBottom: typeof import("../components/NavBottom.vue")['default']
export const LazyNavigation: typeof import("../components/Navigation.vue")['default']
export const LazyNewsletterModal: typeof import("../components/NewsletterModal.vue")['default']
export const LazyNotifications: typeof import("../components/Notifications.vue")['default']
export const LazyNotificationsContent: typeof import("../components/NotificationsContent.vue")['default']
export const LazyOffCanvasMobileMenu: typeof import("../components/OffCanvasMobileMenu.vue")['default']
export const LazyOrderConfirmation: typeof import("../components/OrderConfirmation.vue")['default']
export const LazyOrdersCom: typeof import("../components/OrdersCom.vue")['default']
export const LazyOrdersProfileCom: typeof import("../components/OrdersProfileCom.vue")['default']
export const LazyProductDetailsDescriptionReview: typeof import("../components/ProductDetailsDescriptionReview.vue")['default']
export const LazyQuestionsCont: typeof import("../components/QuestionsCont.vue")['default']
export const LazyRegister: typeof import("../components/Register.vue")['default']
export const LazyResponsiveMobileMenu: typeof import("../components/ResponsiveMobileMenu.vue")['default']
export const LazyReviews: typeof import("../components/Reviews.vue")['default']
export const LazySearch: typeof import("../components/Search.vue")['default']
export const LazyShopContainer: typeof import("../components/ShopContainer.vue")['default']
export const LazyShopSidebar: typeof import("../components/ShopSidebar.vue")['default']
export const LazySuggestionsModal: typeof import("../components/SuggestionsModal.vue")['default']
export const LazyTermsConditionsContainer: typeof import("../components/TermsConditionsContainer.vue")['default']
export const LazyTestimonials: typeof import("../components/Testimonials.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter.vue")['default']
export const LazyTheHeader: typeof import("../components/TheHeader.vue")['default']
export const LazyUnsubscribeContainer: typeof import("../components/UnsubscribeContainer.vue")['default']
export const LazyWelcomeMessage: typeof import("../components/WelcomeMessage.vue")['default']
export const LazyWishListContainer: typeof import("../components/WishListContainer.vue")['default']
export const LazyCheckoutAddressStep: typeof import("../components/checkout/AddressStep.vue")['default']
export const LazyCheckoutCouponForm: typeof import("../components/checkout/CouponForm.vue")['default']
export const LazyCheckoutEmailStep: typeof import("../components/checkout/EmailStep.vue")['default']
export const LazyCheckoutNewProgressBar: typeof import("../components/checkout/NewProgressBar.vue")['default']
export const LazyCheckoutPayStep: typeof import("../components/checkout/PayStep.vue")['default']
export const LazyCheckoutPaypal: typeof import("../components/checkout/Paypal.vue")['default']
export const LazyCheckoutPickupModal: typeof import("../components/checkout/PickupModal.vue")['default']
export const LazyCheckoutRedsysPay: typeof import("../components/checkout/RedsysPay.vue")['default']
export const LazyCheckoutResumen: typeof import("../components/checkout/Resumen.vue")['default']
export const LazyCheckoutSendStep: typeof import("../components/checkout/SendStep.vue")['default']
export const LazyCheckoutSuccessOrder: typeof import("../components/checkout/SuccessOrder.vue")['default']
export const LazyCheckoutTimerNav: typeof import("../components/checkout/TimerNav.vue")['default']
export const LazyHeaderCheckout: typeof import("../components/header/HeaderCheckout.vue")['default']
export const LazyHeroSliderSix: typeof import("../components/hero/HeroSliderSix.vue")['default']
export const LazyPolicyServicePolicyFour: typeof import("../components/policy/ServicePolicyFour.vue")['default']
export const LazyLoadersBigLoader: typeof import("../components/loaders/BigLoader.vue")['default']
export const LazyLoadersSmallLoading: typeof import("../components/loaders/SmallLoading.vue")['default']
export const LazyProfileNewGuest: typeof import("../components/profile/NewGuest.vue")['default']
export const LazyProfileNewProfile: typeof import("../components/profile/NewProfile.vue")['default']
export const LazyProductDetailsWrapper: typeof import("../components/product/ProductDetailsWrapper.vue")['default']
export const LazyProductGridItem: typeof import("../components/product/ProductGridItem.vue")['default']
export const LazyProductGridItemTwo: typeof import("../components/product/ProductGridItemTwo.vue")['default']
export const LazyProductGridStyleThree: typeof import("../components/product/ProductGridStyleThree.vue")['default']
export const LazyProductWrapperCosmetics: typeof import("../components/product/ProductWrapperCosmetics.vue")['default']
export const LazyProductWrapperCosmeticsCart: typeof import("../components/product/ProductWrapperCosmeticsCart.vue")['default']
export const LazyProductWrapperCosmeticsTwo: typeof import("../components/product/ProductWrapperCosmeticsTwo.vue")['default']
export const LazyProductWrapperCosmeticsTwoDetail: typeof import("../components/product/ProductWrapperCosmeticsTwoDetail.vue")['default']
export const componentNames: string[]
