// Generated by nuxi
/// <reference types="@nuxtjs/fontawesome" />
/// <reference types="@nuxtjs/dotenv" />
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="@nuxt/image" />
/// <reference types="@nuxtjs/style-resources" />
/// <reference types="@nuxtjs/axios" />
/// <reference types="@nuxtjs/auth-next" />
/// <reference types="@nuxtjs/sitemap" />
/// <reference types="@nuxtjs/robots" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />
/// <reference path="types/components.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference path="types/nitro.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />

export {}
