// Generated by nuxi
/// <reference types="@nuxtjs/fontawesome" />
/// <reference types="@nuxtjs/dotenv" />
/// <reference types="nuxt-compress" />
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="@nuxt/image" />
/// <reference types="@nuxtjs/style-resources" />
/// <reference types="@nuxtjs/axios" />
/// <reference types="@nuxtjs/auth-next" />
/// <reference types="cookie-universal-nuxt" />
/// <reference types="@nuxt/components" />
/// <reference path="types/components.d.ts" />
/// <reference path="types/schema.d.ts" />
/// <reference types="@pinia/nuxt" />
/// <reference path="types/nitro.d.ts" />
/// <reference path="types/imports.d.ts" />
/// <reference path="imports.d.ts" />

export {}
